apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "yangricardo/hello-go:v4"
          imagePullPolicy: Never
          env:
            - name: "NAME"
              valueFrom:
                configMapKeyRef:
                  key: NAME
                  name: goserver-env
              
            - name: "AGE"
              valueFrom:
                configMapKeyRef:
                  name: goserver-env
                  key: AGE
