apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:      
      volumes:
        - name: myfamily-config
          configMap:
            name: goserver-configmap-family
            items:
              - key: members
                path: "family.txt"    
      containers:
        - name: "goserver"
          image: "yangricardo/hello-go:v8"
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "0.3"
              memory: 20Mi
            limits:
              cpu: "0.3"
              memory: 25Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 4
            failureThreshold: 30
          readinessProbe:
            periodSeconds: 3
            failureThreshold: 1
            # initialDelaySeconds: 10
            httpGet: 
              path: /healthz
              port: 8000    
          livenessProbe:
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
            # initialDelaySeconds: 10
            httpGet: 
              path: /healthz
              port: 8000    
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: myfamily-config