FROM ubuntu:latest

ENTRYPOINT ["echo","Hello"]
#ENTRYPOINT  é uma diretiva que irá definir um comando executável FIXO

CMD ["echo","World"]
#CMD é uma diretiva que irá definir um comando executável default ou que será tratado como parâmetro para o entrypoint