version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=nodedb_pw
      - MYSQL_USER=nodedb_admin
    networks:
      - node_mysql

  app:
    build:
      context: nodejs
    image: yangricardo/nodejs_app
    networks:
      - node_mysql
    volumes:
      - ./nodejs:/usr/src/app
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db

networks:
  node_mysql:
    driver: bridge
