version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_mysql

  app:
    build:
      context: node_app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node_mysql
    volumes:
      - app_volume:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    networks:
      - node_mysql
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  app_volume: {}

networks:
  node_mysql:
    driver: bridge
